module.exports = {
  contacts         :  '2.0/contacts/',
  favorites        :  '2.0/favorites/',
  folders          :  '2.0/folders/',
  groups           :  '2.0/groups/',
  home             :  '2.0/home/',
  imageUrls        :  '2.0/imageurls/',
  reports          :  '2.0/reports/',
  search           :  '2.0/search/',
  server           :  '2.0/serverinfo/',
  sheets           :  '2.0/sheets/',
  sights           :  '2.0/sights/',
  templates        :  '2.0/templates/',
  templatesPublic  :  '2.0/templates/public',
  token            :  '2.0/token',
  users            :  '2.0/users/',
  webhooks         :  '2.0/webhooks/',
  workspaces       :  '2.0/workspaces/'
};
